name: CDN Deployment for AWS
description: Deploys to AWS CDN and optionally invalidates the path in CloudFront
inputs:
  environment:
    description: Environment to deploy to
    default: 'Integ'
  artifact:
    description: Name of the artifact
    required: true
  invalidate_paths:
    description: paths that get invlidate in cloud front
    default: ''
  aws_distribution_id:
    description: The CloudFront description id
    required: true
  aws_bucket_name:
    description: The AWS bucket to sync
    required: true
runs:
  using: "composite"

  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: ./download

    - name: Deploy
      shell: bash
      run: aws s3 sync ./download s3://${{ inputs.aws_bucket_name }}

    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ inputs.aws_distribution_id }}
        PATHS: ${{ inputs.invalidate_paths }}
        AWS_REGION: us-east-2
