on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        default: "Integ"
      artifact:
        type: string
        description: name of the artifact
        default: "secureSignalScript"
      invalidate_paths:
        type: string
        description: paths that get invlidate in cloud front
        default: ""
    secrets:
      AWS_BUCKET_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DISTRIBUTION_ID:
        required: true
jobs:
  deploy_to_CDN:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: ${{ inputs.invalidate_paths }}
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
