name: Publish SDK to NPM and CDN
on:
  workflow_dispatch:
    inputs:
      withTag:
        description: By default, running npm publish will tag your package with the latest dist-tag. To use another dist-tag, please add tag here
        required: false
      publishToNPM:
        description: Publish package to NPM
        required: false
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        target: [development, production]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Package Version
        id: version
        run: |
          echo "::set-output name=package_version::$(cat package.json | jq -r '.version')"
      - name: Install dependencies
        run: npm install
      - name: Build script
        run: npm run build -- --mode=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: uid2SDK-${{ matrix.target }}-${{ steps.version.outputs.package_version }}
          path: ./dist/uid2-sdk-${{ steps.version.outputs.package_version }}.js
    outputs:
      sdkVersion: ${{ steps.version.outputs.package_version }}
  publish-package:
    if: github.event.inputs.publishToNPM == 'true'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Build package
        run: npm run build-package
      - name: Publish Latest package
        if: ${{!github.event.inputs.withTag}}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Latest package with tag
        if: ${{github.event.inputs.withTag}}
        run: npm publish --tag ${{github.event.inputs.withTag}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  cdn-deployment:
    needs: [build]
    strategy:
      matrix:
        environment: [Integ, production]
    uses: ./.github/workflows/aws-cdn-deployment.yml
    with:
      environment: ${{ matrix.environment }}
      artifact: uid2SDK-${{ (matrix.environment == 'Integ' && 'development') || matrix.environment }}-${{ needs.build.outputs.sdkVersion}}
      invalidate_paths: '/uid2-sdk-${{ needs.build.outputs.sdkVersion}}.js'
    secrets:
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
