name: Publish Package to npmjs
on:
  push:
    branches:
      - npm-packaging
jobs:
  verify:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    uses: ./.github/workflows/verify-file-changed.yml
    with:
      files: |
        src/uid2*.ts
        src/Uid2*.ts
  publish:
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - run: npm ci
      - name: Build package
      - run: npm run build-package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
