name: Release Secure Signal Examples Docker Image for UID2 Client Side
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish Pre-release' || format('Release {0}', inputs.release_type)}} Secure Signal Examples Docker Image for UID2 Client Side by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: The type of release
        options:
          - Major
          - Minor
          - Patch
          - Snapshot
        required: true

jobs:
  incrementVersionNumber:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-increase-version-number.yaml@v2
    with:
      release_type: ${{ inputs.release_type }}
      working_dir: examples/google-secure-signals-integration/client_side
    secrets: inherit

  publishForSecureSignalsExampleClientSide:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v3
    needs: incrementVersionNumber
    with:
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: examples/google-secure-signals-integration/client_side/Dockerfile
      docker_context: examples/google-secure-signals-integration/client_side
      docker_image_name: iabtechlab/uid2-secure-signals-example-client-side
      docker_registry: ghcr.io
      force_release: no
    secrets: inherit
