name: Release UID2 Secure Signal Package to CDN

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WORKING_DIR: ./

jobs:
  permissions:
    id-token: write
  verify:
    if: !startsWith(github.event.head_commit.message, 'bump:')
    uses: ./.github/workflows/verify-file-changed.yml
    with:
      files: src/secureSignal.ts
  build:
    needs: [verify]
    if: needs.verify.outputs.isAnyFileModified == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        target: [development, production]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:esp -- --mode=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}SecureSignalScript
          path: ./dist/uid2SecureSignal.js
  deployment:
    needs: [build]
    strategy:
      matrix:
        environment: [Integ, production]
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::475720075663:role/github-runner-for-cdn
    
      - name: Check Identity
        shell: bash
        run: aws sts get-caller-identity

      - uses: ./.github/actions/cdn_deployment_cdn
        with: 
          environment: ${{ matrix.environment }}
          artifact: ${{ (matrix.environment == 'Integ' && 'development') || matrix.environment }}SecureSignalScript
          invalidate_paths: '/uid2SecureSignal.js'
        secrets:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
