name: UID2 Secure Signal Integ CD

on:
  push:
    branches:
      - google-esp-integration
  workflow_dispatch:

env:
  WORKING_DIR: ./

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build
        run: yarn run build:esp
      - uses: actions/upload-artifact@v2
        with:
          name: secureSignalScript
          path: ./dist/uid2SecureSignal.js

  deployment:
    needs: [build]
    uses: ./.github/workflows/aws-cdn-deployment.yml
    with:
      environment: Integ
      artifact: secureSignalScript
      invalidate_paths: "/uid2SecureSignal.js"
    secrets: 
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}

        
