on:
  workflow_call:
    inputs:
      files:
        type: string
        description: file path to check
        default: src/**
    outputs:
      isAnyFileModified:
        description: if any file in the path is modified
        value: ${{ jobs.verify.outputs.isAnyFileModified }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files in the src folder
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ inputs.files }}
      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was modified"
          done
    outputs:
      isAnyFileModified: ${{ steps.changed-files.outputs.any_modified }}
